Repository cybermm/vpn-akms, pull requests merged in 2022-09, with the labels that each got.

#13 update: init vite, changing documentation and formatting code style
  .env.example
  .gitattributes
  .gitignore
  CONTRIBUTING.md
  README.md
  code_of_conduct.md
  composer.json
  composer.lock
  contributing.md
  license.md
  package-lock.json
  package.json
  postcss.config.js
  prettier.config.js
  readme.md
  resources/css/app.css
  resources/js/app.js
  resources/js/bootstrap.js
  resources/views/admin/index.blade.php
  resources/views/admin/login.blade.php
  resources/views/admin/register.blade.php
  resources/views/index.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/footer.blade.php
  resources/views/layouts/navbar.blade.php
  resources/views/server/create.blade.php
  resources/views/server/edit.blade.php
  tailwind.config.js
  vite.config.js
  webpack.mix.js
Labels: update

#22 feat: home ui created
  figma/home.fig
Labels: feat

#25 feat: auth ui created
  figma/auth.fig
Labels: feat

#26 feat: add home page
  app/Http/Controllers/LoginController.php
  app/Http/Controllers/PageController.php
  app/Http/Controllers/ServerController.php
  app/Http/Controllers/UserController.php
  app/Http/Requests/CreateServerRequest.php
  app/Http/Requests/LoginRequest.php
  app/Http/Requests/UserRequest.php
  app/Models/Server.php
  app/Models/User.php
  artisan
  figma/auth.fig
  figma/home.fig
  package-lock.json
  package.json
  resources/css/app.css
  resources/js/App.vue
  resources/js/app.js
  resources/js/assets/images/cover/black-1k.png
  resources/js/assets/images/cover/black-4k.png
  resources/js/assets/images/cover/transparent-1k.png
  resources/js/assets/images/cover/transparent-4k.png
  resources/js/assets/images/logo/black-1k.png
  resources/js/assets/images/logo/black-4k.png
  resources/js/assets/images/logo/transparent-1k.png
  resources/js/assets/images/logo/transparent-4k.png
  resources/js/bootstrap.js
  resources/js/components/BaseHeader.vue
  resources/js/components/BaseHero.vue
  resources/js/components/BaseTable.vue
  resources/js/views/BaseFooter.vue
  resources/views/admin/index.blade.php
  resources/views/admin/login.blade.php
  resources/views/admin/register.blade.php
  resources/views/index.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/footer.blade.php
  resources/views/layouts/navbar.blade.php
  resources/views/main.blade.php
  resources/views/server/create.blade.php
  resources/views/server/edit.blade.php
  routes/web.php
  tailwind.config.js
  vite.config.js
Labels: feat

#29 fix: changing ui
  figma/auth.fig
  figma/home.fig
Labels: fix
